// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: proto/message.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgType int32

const (
	MsgType_CHAT          MsgType = 0
	MsgType_SYSTEM        MsgType = 1
	MsgType_HEARTBEAT     MsgType = 2
	MsgType_BURN_RECEIPT  MsgType = 3
	MsgType_PEER_DISCOVER MsgType = 4
	MsgType_PRIVATE_CHAT  MsgType = 5
	MsgType_RENAME        MsgType = 6
	MsgType_WHO           MsgType = 7
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "CHAT",
		1: "SYSTEM",
		2: "HEARTBEAT",
		3: "BURN_RECEIPT",
		4: "PEER_DISCOVER",
		5: "PRIVATE_CHAT",
		6: "RENAME",
		7: "WHO",
	}
	MsgType_value = map[string]int32{
		"CHAT":          0,
		"SYSTEM":        1,
		"HEARTBEAT":     2,
		"BURN_RECEIPT":  3,
		"PEER_DISCOVER": 4,
		"PRIVATE_CHAT":  5,
		"RENAME":        6,
		"WHO":           7,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_message_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_proto_message_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{0}
}

type SystemType int32

const (
	SystemType_SYS_JOIN   SystemType = 0
	SystemType_SYS_LEAVE  SystemType = 1
	SystemType_SYS_RENAME SystemType = 2
	SystemType_SYS_ERROR  SystemType = 3
)

// Enum value maps for SystemType.
var (
	SystemType_name = map[int32]string{
		0: "SYS_JOIN",
		1: "SYS_LEAVE",
		2: "SYS_RENAME",
		3: "SYS_ERROR",
	}
	SystemType_value = map[string]int32{
		"SYS_JOIN":   0,
		"SYS_LEAVE":  1,
		"SYS_RENAME": 2,
		"SYS_ERROR":  3,
	}
)

func (x SystemType) Enum() *SystemType {
	p := new(SystemType)
	*p = x
	return p
}

func (x SystemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SystemType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_message_proto_enumTypes[1].Descriptor()
}

func (SystemType) Type() protoreflect.EnumType {
	return &file_proto_message_proto_enumTypes[1]
}

func (x SystemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SystemType.Descriptor instead.
func (SystemType) EnumDescriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{1}
}

type WsMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MessageId string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Timestamp int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type      MsgType                `protobuf:"varint,3,opt,name=type,proto3,enum=proto.MsgType" json:"type,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WsMessage_Chat
	//	*WsMessage_System
	//	*WsMessage_Hb
	//	*WsMessage_Receipt
	//	*WsMessage_Peer
	Payload       isWsMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WsMessage) Reset() {
	*x = WsMessage{}
	mi := &file_proto_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WsMessage) ProtoMessage() {}

func (x *WsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WsMessage.ProtoReflect.Descriptor instead.
func (*WsMessage) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{0}
}

func (x *WsMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *WsMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *WsMessage) GetType() MsgType {
	if x != nil {
		return x.Type
	}
	return MsgType_CHAT
}

func (x *WsMessage) GetPayload() isWsMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WsMessage) GetChat() *ChatMessage {
	if x != nil {
		if x, ok := x.Payload.(*WsMessage_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *WsMessage) GetSystem() *SystemNotice {
	if x != nil {
		if x, ok := x.Payload.(*WsMessage_System); ok {
			return x.System
		}
	}
	return nil
}

func (x *WsMessage) GetHb() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*WsMessage_Hb); ok {
			return x.Hb
		}
	}
	return nil
}

func (x *WsMessage) GetReceipt() *BurnReceipt {
	if x != nil {
		if x, ok := x.Payload.(*WsMessage_Receipt); ok {
			return x.Receipt
		}
	}
	return nil
}

func (x *WsMessage) GetPeer() *PeerInfo {
	if x != nil {
		if x, ok := x.Payload.(*WsMessage_Peer); ok {
			return x.Peer
		}
	}
	return nil
}

type isWsMessage_Payload interface {
	isWsMessage_Payload()
}

type WsMessage_Chat struct {
	Chat *ChatMessage `protobuf:"bytes,10,opt,name=chat,proto3,oneof"`
}

type WsMessage_System struct {
	System *SystemNotice `protobuf:"bytes,11,opt,name=system,proto3,oneof"`
}

type WsMessage_Hb struct {
	Hb *Heartbeat `protobuf:"bytes,12,opt,name=hb,proto3,oneof"`
}

type WsMessage_Receipt struct {
	Receipt *BurnReceipt `protobuf:"bytes,13,opt,name=receipt,proto3,oneof"`
}

type WsMessage_Peer struct {
	Peer *PeerInfo `protobuf:"bytes,14,opt,name=peer,proto3,oneof"`
}

func (*WsMessage_Chat) isWsMessage_Payload() {}

func (*WsMessage_System) isWsMessage_Payload() {}

func (*WsMessage_Hb) isWsMessage_Payload() {}

func (*WsMessage_Receipt) isWsMessage_Payload() {}

func (*WsMessage_Peer) isWsMessage_Payload() {}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	BurnSeconds   int32                  `protobuf:"varint,4,opt,name=burn_seconds,json=burnSeconds,proto3" json:"burn_seconds,omitempty"`
	BurnedAt      int64                  `protobuf:"varint,5,opt,name=burned_at,json=burnedAt,proto3" json:"burned_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_proto_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{1}
}

func (x *ChatMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ChatMessage) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetBurnSeconds() int32 {
	if x != nil {
		return x.BurnSeconds
	}
	return 0
}

func (x *ChatMessage) GetBurnedAt() int64 {
	if x != nil {
		return x.BurnedAt
	}
	return 0
}

type SystemNotice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          SystemType             `protobuf:"varint,1,opt,name=type,proto3,enum=proto.SystemType" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemNotice) Reset() {
	*x = SystemNotice{}
	mi := &file_proto_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemNotice) ProtoMessage() {}

func (x *SystemNotice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemNotice.ProtoReflect.Descriptor instead.
func (*SystemNotice) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{2}
}

func (x *SystemNotice) GetType() SystemType {
	if x != nil {
		return x.Type
	}
	return SystemType_SYS_JOIN
}

func (x *SystemNotice) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SystemNotice) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PingTs        int64                  `protobuf:"varint,1,opt,name=ping_ts,json=pingTs,proto3" json:"ping_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetPingTs() int64 {
	if x != nil {
		return x.PingTs
	}
	return 0
}

type BurnReceipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	BurnedAt      int64                  `protobuf:"varint,2,opt,name=burned_at,json=burnedAt,proto3" json:"burned_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BurnReceipt) Reset() {
	*x = BurnReceipt{}
	mi := &file_proto_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BurnReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BurnReceipt) ProtoMessage() {}

func (x *BurnReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BurnReceipt.ProtoReflect.Descriptor instead.
func (*BurnReceipt) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{4}
}

func (x *BurnReceipt) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *BurnReceipt) GetBurnedAt() int64 {
	if x != nil {
		return x.BurnedAt
	}
	return 0
}

type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Addr          string                 `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	WsPort        int32                  `protobuf:"varint,4,opt,name=ws_port,json=wsPort,proto3" json:"ws_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_proto_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{5}
}

func (x *PeerInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PeerInfo) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *PeerInfo) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *PeerInfo) GetWsPort() int32 {
	if x != nil {
		return x.WsPort
	}
	return 0
}

var File_proto_message_proto protoreflect.FileDescriptor

const file_proto_message_proto_rawDesc = "" +
	"\n" +
	"\x13proto/message.proto\x12\x05proto\"\xcb\x02\n" +
	"\tWsMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\"\n" +
	"\x04type\x18\x03 \x01(\x0e2\x0e.proto.MsgTypeR\x04type\x12(\n" +
	"\x04chat\x18\n" +
	" \x01(\v2\x12.proto.ChatMessageH\x00R\x04chat\x12-\n" +
	"\x06system\x18\v \x01(\v2\x13.proto.SystemNoticeH\x00R\x06system\x12\"\n" +
	"\x02hb\x18\f \x01(\v2\x10.proto.HeartbeatH\x00R\x02hb\x12.\n" +
	"\areceipt\x18\r \x01(\v2\x12.proto.BurnReceiptH\x00R\areceipt\x12%\n" +
	"\x04peer\x18\x0e \x01(\v2\x0f.proto.PeerInfoH\x00R\x04peerB\t\n" +
	"\apayload\"\x8b\x01\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12!\n" +
	"\fburn_seconds\x18\x04 \x01(\x05R\vburnSeconds\x12\x1b\n" +
	"\tburned_at\x18\x05 \x01(\x03R\bburnedAt\"c\n" +
	"\fSystemNotice\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.proto.SystemTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\"$\n" +
	"\tHeartbeat\x12\x17\n" +
	"\aping_ts\x18\x01 \x01(\x03R\x06pingTs\"I\n" +
	"\vBurnReceipt\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tburned_at\x18\x02 \x01(\x03R\bburnedAt\"m\n" +
	"\bPeerInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12\x12\n" +
	"\x04addr\x18\x03 \x01(\tR\x04addr\x12\x17\n" +
	"\aws_port\x18\x04 \x01(\x05R\x06wsPort*z\n" +
	"\aMsgType\x12\b\n" +
	"\x04CHAT\x10\x00\x12\n" +
	"\n" +
	"\x06SYSTEM\x10\x01\x12\r\n" +
	"\tHEARTBEAT\x10\x02\x12\x10\n" +
	"\fBURN_RECEIPT\x10\x03\x12\x11\n" +
	"\rPEER_DISCOVER\x10\x04\x12\x10\n" +
	"\fPRIVATE_CHAT\x10\x05\x12\n" +
	"\n" +
	"\x06RENAME\x10\x06\x12\a\n" +
	"\x03WHO\x10\a*H\n" +
	"\n" +
	"SystemType\x12\f\n" +
	"\bSYS_JOIN\x10\x00\x12\r\n" +
	"\tSYS_LEAVE\x10\x01\x12\x0e\n" +
	"\n" +
	"SYS_RENAME\x10\x02\x12\r\n" +
	"\tSYS_ERROR\x10\x03B+Z)github.com/Yorha9e/golang-im-system/protob\x06proto3"

var (
	file_proto_message_proto_rawDescOnce sync.Once
	file_proto_message_proto_rawDescData []byte
)

func file_proto_message_proto_rawDescGZIP() []byte {
	file_proto_message_proto_rawDescOnce.Do(func() {
		file_proto_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_message_proto_rawDesc), len(file_proto_message_proto_rawDesc)))
	})
	return file_proto_message_proto_rawDescData
}

var file_proto_message_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_message_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_message_proto_goTypes = []any{
	(MsgType)(0),         // 0: proto.MsgType
	(SystemType)(0),      // 1: proto.SystemType
	(*WsMessage)(nil),    // 2: proto.WsMessage
	(*ChatMessage)(nil),  // 3: proto.ChatMessage
	(*SystemNotice)(nil), // 4: proto.SystemNotice
	(*Heartbeat)(nil),    // 5: proto.Heartbeat
	(*BurnReceipt)(nil),  // 6: proto.BurnReceipt
	(*PeerInfo)(nil),     // 7: proto.PeerInfo
}
var file_proto_message_proto_depIdxs = []int32{
	0, // 0: proto.WsMessage.type:type_name -> proto.MsgType
	3, // 1: proto.WsMessage.chat:type_name -> proto.ChatMessage
	4, // 2: proto.WsMessage.system:type_name -> proto.SystemNotice
	5, // 3: proto.WsMessage.hb:type_name -> proto.Heartbeat
	6, // 4: proto.WsMessage.receipt:type_name -> proto.BurnReceipt
	7, // 5: proto.WsMessage.peer:type_name -> proto.PeerInfo
	1, // 6: proto.SystemNotice.type:type_name -> proto.SystemType
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_message_proto_init() }
func file_proto_message_proto_init() {
	if File_proto_message_proto != nil {
		return
	}
	file_proto_message_proto_msgTypes[0].OneofWrappers = []any{
		(*WsMessage_Chat)(nil),
		(*WsMessage_System)(nil),
		(*WsMessage_Hb)(nil),
		(*WsMessage_Receipt)(nil),
		(*WsMessage_Peer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_message_proto_rawDesc), len(file_proto_message_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_message_proto_goTypes,
		DependencyIndexes: file_proto_message_proto_depIdxs,
		EnumInfos:         file_proto_message_proto_enumTypes,
		MessageInfos:      file_proto_message_proto_msgTypes,
	}.Build()
	File_proto_message_proto = out.File
	file_proto_message_proto_goTypes = nil
	file_proto_message_proto_depIdxs = nil
}
